### ISSUE TITLE
JDK8 Optional behaves different from Guava Optional on serialization

### ISSUE THREAD

**Issue by hgschmie** [FasterXML/jackson-datatype-jdk8#10]
Using this test class:

```java
package jackson;

import static org.junit.Assert.assertEquals;

import java.util.Map;

import org.junit.Test;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.datatype.guava.GuavaModule;
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module;
import com.google.common.collect.ImmutableMap;

public class OptionalTest
{
    public ObjectMapper getObjectMapper(JsonInclude.Include mode)
        throws Exception
    {
        ObjectMapper objectMapper = new ObjectMapper();
        objectMapper.setSerializationInclusion(mode);
        objectMapper.registerModule(new GuavaModule());
        objectMapper.registerModule(new Jdk8Module());
        return objectMapper;
    }

    @Test
    public void testOptionalAbsentNonNull()
        throws Exception
    {
        ObjectMapper objectMapper = getObjectMapper(JsonInclude.Include.NON_NULL);

        GuavaTestBean guavaBean = new GuavaTestBean(com.google.common.base.Optional.absent(), ImmutableMap.<String, String>of());
        Jdk8TestBean jdk8Bean = new Jdk8TestBean(java.util.Optional.<String>empty(), ImmutableMap.<String, String>of());

        String guavaResult = objectMapper.writeValueAsString(guavaBean);
        String jdk8Result = objectMapper.writeValueAsString(jdk8Bean);

        assertEquals(guavaResult, jdk8Result);
        assertEquals("{\"map\":{}}", guavaResult);
    }

    @Test
    public void testMapOptionalAbsentNonNull()
        throws Exception
    {
        ObjectMapper objectMapper = getObjectMapper(JsonInclude.Include.NON_NULL);

        ImmutableMap<String, Object> guavaMap = ImmutableMap.<String, Object>of(
            "key", com.google.common.base.Optional.absent(),
            "map", ImmutableMap.<String, String>of());
        ImmutableMap<String, Object> jdk8Map = ImmutableMap.<String, Object>of(
            "key", java.util.Optional.empty(),
            "map", ImmutableMap.<String, String>of());

        String guavaResult = objectMapper.writeValueAsString(guavaMap);
        String jdk8Result = objectMapper.writeValueAsString(jdk8Map);

        assertEquals(guavaResult, jdk8Result);
        assertEquals("{\"map\":{}}", guavaResult);
    }

    @Test
    public void testGuavaOptionalAbsentBeanVsMap()
        throws Exception
    {
        ObjectMapper objectMapper = getObjectMapper(JsonInclude.Include.NON_NULL);

        GuavaTestBean guavaBean = new GuavaTestBean(com.google.common.base.Optional.absent(), ImmutableMap.<String, String>of());
        ImmutableMap<String, Object> guavaMap = ImmutableMap.<String, Object>of(
            "key", com.google.common.base.Optional.absent(),
            "map", ImmutableMap.<String, String>of());

        String guavaBeanResult = objectMapper.writeValueAsString(guavaBean);
        String guavaMapResult = objectMapper.writeValueAsString(guavaMap);

        assertEquals(guavaBeanResult, guavaMapResult);
        assertEquals("{\"map\":{}}", guavaBeanResult);
    }

    @Test
    public void testJdk8OptionalAbsentBeanVsMap()
        throws Exception
    {
        ObjectMapper objectMapper = getObjectMapper(JsonInclude.Include.NON_NULL);

        Jdk8TestBean jdk8Bean = new Jdk8TestBean(java.util.Optional.<String>empty(), ImmutableMap.<String, String>of());
        ImmutableMap<String, Object> jdk8Map = ImmutableMap.<String, Object>of(
            "key", java.util.Optional.empty(),
            "map", ImmutableMap.<String, String>of());

        String jdk8BeanResult = objectMapper.writeValueAsString(jdk8Bean);
        String jdk8MapResult = objectMapper.writeValueAsString(jdk8Map);

        assertEquals(jdk8BeanResult, jdk8MapResult);
        assertEquals("{\"map\":{}}", jdk8BeanResult);
    }

    public static class GuavaTestBean
    {
        private final com.google.common.base.Optional<String> key;
        private final Map<String, String> map;

        @JsonCreator
        public GuavaTestBean(@JsonProperty("key") com.google.common.base.Optional<String> key,
                             @JsonProperty("map") Map<String, String> map)
        {
            this.key = key;
            this.map = map;
        }

        @JsonProperty
        public com.google.common.base.Optional<String> getKey()
        {
            return key;
        }

        @JsonProperty
        public Map<String, String> getMap()
        {
            return map;
        }
    }

    public static class Jdk8TestBean
    {
        private final java.util.Optional<String> key;
        private final Map<String, String> map;

        @JsonCreator
        public Jdk8TestBean(@JsonProperty("key") java.util.Optional<String> key,
                            @JsonProperty("map") Map<String, String> map)
        {
            this.key = key;
            this.map = map;
        }

        @JsonProperty
        public java.util.Optional<String> getKey()
        {
            return key;
        }

        @JsonProperty
        public Map<String, String> getMap()
        {
            return map;
        }
    }
}
```

results in

```
Running jackson.OptionalTest
Tests run: 4, Failures: 4, Errors: 0, Skipped: 0, Time elapsed: 0.444 sec <<< FAILURE! - in jackson.OptionalTest
testOptionalAbsentNonNull(jackson.OptionalTest)  Time elapsed: 0.003 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<{"[]map":{}}> but was:<{"[key":null,"]map":{}}>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at jackson.OptionalTest.testOptionalAbsentNonNull(OptionalTest.java:41)
```

When using `JsonInclude.Include.NON_NULL`, a bean attribute using an Optional serializes differently for a Guava Optional and a JDK8 Optional. These should serialize the same. This was verified with Jackson 2.6.0-rc2-SNAPSHOT (current trunk) and Jackson 2.4.7-SNAPSHOT (current 2.4 branch).  A Guava optional does not (IMHO correctly) show up with a null value in the resulting JSON, while a JDK8 Optional does.

```
testMapOptionalAbsentNonNull(jackson.OptionalTest)  Time elapsed: 0.403 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<{"[]map":{}}> but was:<{"[key":null,"]map":{}}>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at jackson.OptionalTest.testMapOptionalAbsentNonNull(OptionalTest.java:62)
```

When serializing an equivalent Map (containing two elements, one being an empty map, the other an Optional, the result is different from the expected serialization result of a bean. Where a bean would not contain the "null" value for the key property, the map does contain the null value for the key property. I have found no way to turn this off (any of the five `JsonInclude.Include` options).

```
testGuavaOptionalAbsentBeanVsMap(jackson.OptionalTest)  Time elapsed: 0.03 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<{"[]map":{}}> but was:<{"[key":null,"]map":{}}>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at jackson.OptionalTest.testGuavaOptionalAbsentBeanVsMap(OptionalTest.java:79)
```

When comparing the map result to the bean result, for a Guava bean, the results are different.

```
testJdk8OptionalAbsentBeanVsMap(jackson.OptionalTest)  Time elapsed: 0.006 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<{"[]map":{}}> but was:<{"[key":null,"]map":{}}>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at jackson.OptionalTest.testJdk8OptionalAbsentBeanVsMap(OptionalTest.java:98)
```

When comparing the map result to the bean result, for a JDK8 bean, the results are the same (good). but still contain the `"key":null` value which should be present neither in the bean nor in the map.

```
Results :

Failed tests: 
  OptionalTest.testGuavaOptionalAbsentBeanVsMap:79 expected:<{"[]map":{}}> but was:<{"[key":null,"]map":{}}>
  OptionalTest.testJdk8OptionalAbsentBeanVsMap:98 expected:<{"[]map":{}}> but was:<{"[key":null,"]map":{}}>
  OptionalTest.testMapOptionalAbsentNonNull:62 expected:<{"[]map":{}}> but was:<{"[key":null,"]map":{}}>
  OptionalTest.testOptionalAbsentNonNull:41 expected:<{"[]map":{}}> but was:<{"[key":null,"]map":{}}>
```

I would expect all four of these tests to pass with Jackson.

**Comment by cowtowncoder** [comment]
One more thing to try out is the new setting for `GuavaModule`, changeable with `configureAbsentsAsNulls()`. Default is `true`, for things to work the same as in 2.5.
This is different from how referential types (such as various Optionals) should work, overall, with 2.6 and beyond.

It is possible that serialization exclusion for `MapSerializer` might be incorrect, perhaps it could be missing handling of `NON_ABSENT`.

**Comment by hgschmie** [comment]
BTW; adding `objectMapper.disable(SerializationFeature.WRITE_NULL_MAP_VALUES);` to the object mapper makes no difference.

**Comment by hgschmie** [comment]
Neither `objectMapper.registerModule(new GuavaModule().configureAbsentsAsNulls(false));` nor `objectMapper.registerModule(new GuavaModule().configureAbsentsAsNulls(true));` makes any difference.

**Comment by cowtowncoder** [comment]
I think that it starts from handling of "suppressableValue" for `MapSerializer`. This comes, fundamentally, from `BasicSerializerFactory`, line 787 or so:

```java
    protected Object findSuppressableContentValue(SerializationConfig config,
            JavaType contentType, BeanDescription beanDesc)
        throws JsonMappingException
    {
        JsonInclude.Include incl = beanDesc.findSerializationInclusionForContent(null);

        if (incl != null) {
            switch (incl) {
            case NON_DEFAULT:
                // 19-Oct-2014, tatu: Not sure what this'd mean; so take it to mean "NON_EMPTY"...
                incl = JsonInclude.Include.NON_EMPTY;
                break;
            default:
                // all other modes actually good as is, unless we'll find better ways
                break;
            }
            return incl;
        }
        return null;
    }
```

which is missing handling for `NON_EMPTY`, and `NON_ABSENT` as well.
Whether fixing this (to do something similar to `PropertyBuilder`, line 101 or so) is sufficient is not clear; perhaps `MapSerializer` needs more handling. But I think I may have missed some part of changes with `NON_ABSENT` work.

A related question, then, is what to do with `WRITE_NULL_MAP_VALUES`. Since definition of "NON_NULL" in 2.6 is strictly only Java `null` (there's longer discussion on "why?" part -- has to do with rount-tripping of optionals, complexity in supporting detection of null-referencing referential type), there isn't global setting for excluding "absent" optionals.
But maybe there should be. Features are bit unwieldy here, but it may be necessary to either add yet one more, `WRITE_ABSENT_MAP_VALUES`, or something like "Do consider absents like nulls".
Perhaps first option is slightly less ugly. But it does have some backwards compatibility aspects too (wrt Guava Optionals having been considered "real nulls" in the past, and with default settings even for 2.6).

**Comment by cowtowncoder** [comment]
Looking bit deeper, I was wrong: that piece of code is ok. But handling in `MapSerializer` needed some improvements.
So I checked in a fix in `jackson-databind` that should now make `Map`s handling of NON_ABSENT (via annotation, or global default) work.

I think there is still need for a new feature; will probably file it soon.

**Comment by cowtowncoder** [comment]
I think the changes to allow handling identical to Guava's optional did implement this. Closing.
