### ISSUE TITLE
Jackson JDK8 Data Type and Parameter Names modules don't play together?

### ISSUE THREAD

**Issue by ekis** [FasterXML/jackson-datatype-jdk8#16]
Not sure if I should be putting this issue on this project or `jackson-parameter-names`, so I'll crosspost.

The issue synopsis is given [here](http://stackoverflow.com/questions/32724292/jackson-jdk8-data-type-and-parameter-names-modules-dont-play-together) - essentially, it seems as Parameter Names module does not work with JDK8 `Optional<T>`, requiring the constructor to be peppered with `@JsonProperty("propertyName")` code.

Am I doing something wrong, is there a limitation in `javac` or in one of the modules?

**Comment by cowtowncoder** [comment]
I suspect this is due to one remaining problem with Jackson `databind` and its handling of Creator methods (constructors, static factory methods): although it SHOULD infer intent for a constructor to be a Creator, it can not as things are with 2.6. Reasons for this are complex, and it was not found out until late in 2.6 dev cycle, but the result is that you typically do need to add `@JsonCreator` annotation to mark constructor.

So, it should NOT be necessary to use `@JsonProperty`, with parameter names module.
But you may have to use `@JsonCreator`. In addition, for single-argument constructors, you further want to indicate it is NOT a delegating creator (where the only argument is bound from JSON directly, and not as property), with `@JsonCreator(mode=Mode.PROPERTIES)`.

We hope to fix the flaw in 2.7, to remove need for `@JsonCreator`.

Let me know if addition of `@JsonCreator` does not fix the issue. I am not sure if and how `Optional` would be related here.

**Comment by ekis** [comment]
It does not - adding `@JsonCreator` without any annotation on the constructor yields the following stacktrace:

```
com.fasterxml.jackson.databind.JsonMappingException: Argument #0 of constructor [constructor for com._3esi.load.bootstrap.ScratchPad$SimpleTest, annotations: {interface com.fasterxml.jackson.annotation.JsonCreator=@com.fasterxml.jackson.annotation.JsonCreator(mode=DEFAULT)}] has no property name annotation; must have name when multiple-parameter constructor annotated as Creator
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:269)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:461)
	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:3833)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3727)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2724)
```

It *does* work as long as `Optional` type is not involved. Even more so, as long as there is not `Optional`, if I annotate just the fields with `@JsonProperty` - no annotation is needed on the constructor at all (I have read somewhere `@JsonCreator` is really needed to resolve constructor ambiguities). 

Perhaps Luka on the other had a point about JDK8 lacking the `-parameters` option?

**Comment by cowtowncoder** [comment]
@ekis Keep in mind that if you use `@JsonProperty` on fields, Jackson is happy to use fields for deserialization; it does not need the constructor. Exception you are getting when marking constructor, however, points out that databind is now expecting to use the constructor, but is missing name information indeed.

I am puzzled by link to `Optional`, as that should not have effect at this level. But perhaps there is something going on with its interaction.

On stack trace: would it be possible to get trace for the root cause? `JsonMappingException` here wraps the original cause; I would be interested in seeing whether it is missing the "implicit" name (from Java 8 bytecode), or is expecting explicit name (from annotation).

**Comment by ekis** [comment]
@cowtowncoder 

Certainly, here is the full stacktrace - I do not know if I can get hold of the `33 more` lines.
The stacktrace is the result of running the test on this container:
```
    private static class SimpleTest {
        private Optional<String> s1;
        private Optional<String> s2;
        private Map<String, String> map;

        @JsonCreator
        private SimpleTest(Optional<String> s1, Optional<String> s2, Map<String, String> map) {
            this.s1 = s1;
            this.s2 = s2;
            this.map = map;
        }

        static SimpleTest of(Optional<String> s1, Optional<String> s2, Map<String, String> m) {
            return new SimpleTest(s1, s2, m);
        }
    }
```

```
com.fasterxml.jackson.databind.JsonMappingException: Argument #0 of constructor [constructor for com._3esi.load.bootstrap.ScratchPad$SimpleTest, annotations: {interface com.fasterxml.jackson.annotation.JsonCreator=@com.fasterxml.jackson.annotation.JsonCreator(mode=DEFAULT)}] has no property name annotation; must have name when multiple-parameter constructor annotated as Creator
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:269)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:461)
	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:3833)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3727)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2724)
	at test.testDeser(ScratchPad.java:186)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.IllegalArgumentException: Argument #0 of constructor [constructor for com._3esi.load.bootstrap.ScratchPad$SimpleTest, annotations: {interface com.fasterxml.jackson.annotation.JsonCreator=@com.fasterxml.jackson.annotation.JsonCreator(mode=DEFAULT)}] has no property name annotation; must have name when multiple-parameter constructor annotated as Creator
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._addDeserializerConstructors(BasicDeserializerFactory.java:512)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._constructDefaultValueInstantiator(BasicDeserializerFactory.java:324)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findValueInstantiator(BasicDeserializerFactory.java:254)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:222)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:142)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:403)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:352)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
	... 33 more
```

**Comment by ekis** [comment]
Tatu, both serialization and deserialization with or without `@JsonCreator` specified - IDEA has been playing tricks with us all as the javac `-parameter` somehow vanished from compiler settings.

To be precise, this works both ways:
```
    @Test
    public void testSer() throws JsonProcessingException {
        SimpleTest test = SimpleTest.of(Optional.of("a"), Optional.empty(), Collections.emptyMap());
        System.out.println(JacksonUtil.getMapper().writeValueAsString(test));
    }

    @Test
    public void testDeser() throws IOException {
        String json = "{\n" +
                "  \"s1\" : \"a\",\n" +
                "  \"map\" : { }\n" +
                "}";
        JacksonUtil.getMapper().readValue(json, SimpleTest.class);
    }

    private static class SimpleTest {
        @JsonProperty private Optional<String> s1;
        @JsonProperty private Optional<String> s2;
        @JsonProperty private Map<String, String> map;

        // @JsonCreator is optional here
        private SimpleTest(Optional<String> s1, Optional<String> s2, Map<String, String> map) {
            this.s1 = s1;
            this.s2 = s2;
            this.map = map;
        }

        static SimpleTest of(Optional<String> s1, Optional<String> s2, Map<String, String> m) {
            return new SimpleTest(s1, s2, m);
        }
    }
```
It is interesting to note the serializer doesn't work _without_ `@JsonProperty` annotation but the annotation itself doesn't require any values. That is as expected?

**Comment by ekis** [comment]
Issue is most likely caused by wrong IDE settings: `-parameters` javac disappeared from compiler options.

I'll be closing the issue.
Thank you for your time and help.

**Comment by cowtowncoder** [comment]
@ekis Thank you for updates & good luck!
