### ISSUE TITLE
fails to serialize empty Optional with @JsonUnwrapped annotation

### ISSUE THREAD

**Issue by osi** [FasterXML/jackson-datatype-jdk8#20]
Trying to serialize an empty java.util.Optional that has a JsonUnwrapped annotation fails:

```
com.fasterxml.jackson.core.JsonGenerationException: Can not write a null, expecting field name

	at com.fasterxml.jackson.core.JsonGenerator._reportError(JsonGenerator.java:1649)
	at com.fasterxml.jackson.core.json.WriterBasedJsonGenerator._verifyValueWrite(WriterBasedJsonGenerator.java:775)
	at com.fasterxml.jackson.core.json.WriterBasedJsonGenerator.writeNull(WriterBasedJsonGenerator.java:754)
	at com.fasterxml.jackson.databind.ser.std.NullSerializer.serialize(NullSerializer.java:30)
	at com.fasterxml.jackson.databind.SerializerProvider.defaultSerializeNull(SerializerProvider.java:1063)
	at com.fasterxml.jackson.datatype.jdk8.OptionalSerializer.serialize(OptionalSerializer.java:135)
	at com.fasterxml.jackson.datatype.jdk8.OptionalSerializer.serialize(OptionalSerializer.java:16)
	at com.fasterxml.jackson.databind.ser.impl.UnwrappingBeanPropertyWriter.serializeAsField(UnwrappingBeanPropertyWriter.java:127)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:675)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:157)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:130)
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3554)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:2925)
```

```java
import com.fasterxml.jackson.annotation.JsonUnwrapped;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module;
import org.junit.Test;

import java.util.Optional;

import static org.junit.Assert.assertEquals;

public class UnwrappedOptionalTest {
    @Test
    public void shouldSerializeUnwrappedOptional() throws Exception {
        ObjectMapper mapper = new ObjectMapper().registerModule(new Jdk8Module());

        assertEquals("{\"id\":\"foo\"}", mapper.writeValueAsString(new Bean("foo", Optional.<Bean2>empty())));
    }
}

class Bean {
    public String id;
    @JsonUnwrapped(prefix="child")
    public Optional<Bean2> bean2;

    public Bean(String id, Optional<Bean2> bean2) {
        this.id = id;
        this.bean2 = bean2;
    }
}

class Bean2 {
    public String name;
}
```

**Comment by osi** [comment]
I've worked around for now by adding a serializer modifier that looks for this case and uses a custom subclass of OptionalSerializer that first does the following check on serialization

```java
            if (isUnwrappingSerializer() && !opt.isPresent()) {
                return;
            }
```

**Comment by cowtowncoder** [comment]
I'll have a look. Is this with version 2.6.3? Mostly asking since I have worked actively on trying to support `Optional`s better.

**Comment by cowtowncoder** [comment]
I can reproduce this with 2.6.3.

I assume suggested behavior of basically skipping `null` unwrapped value makes sense; can not think of anything actually better.

**Comment by osi** [comment]
I observed this against 2.6.2.

And agreed on just skipping an empty optional when unwrapped makes sense.

(although I could see additional complexity if the unwrapped optional had JsonInclude annotations that specified it should always be included, but I'm not sure how that works in the non-Optional case anyways)

Thanks for the quick response!

**Comment by cowtowncoder** [comment]
Right; the problem being that being unwrapped, it is not exactly clear how otherwise it could be handled; what property name should be used (one MUST be used at that point) and so on.
Inclusion filtering is indeed a tricky problem with `Optional` and similar reference types: more work is done for 2.7 to allow distinction between emptiness of the type itself (does Optional have any content?), and possibly emptiness (etc) of the content/referenced value. This affects serialization of `Map`s, and ideally would allow multi-level emptiness checks for POJOs... but we'll see how far that can go.
