### ISSUE TITLE
Cannot deserialize a simple entity containing an Optional<String>

### ISSUE THREAD

**Issue by shanloid** [FasterXML/jackson-datatype-jdk8#4]
Using version 2.5.1 (same error occurred on 2.5.0), I'm seeing the following error when trying to deserialize a simple entity that contains a single Optional<String> field (serialization works ok, FWIW):

com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of FIELD_NAME token
 at [Source: {"data":"foo"}; line: 1, column: 2]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:835)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:59)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:12)
	at com.fasterxml.jackson.datatype.jdk8.OptionalDeserializer.deserialize(OptionalDeserializer.java:98)
	at com.fasterxml.jackson.datatype.jdk8.OptionalDeserializer.deserialize(OptionalDeserializer.java:18)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1069)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:295)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:142)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3562)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2578)

Note that I get this error regardless of whether my Optional is empty or not. I noticed that the unit tests you've got only test serialization/deserialization of Optionals as top-level entities, not as fields within entities.

Happy to provide a small test class that produces this error if requested, but it's trivial to reproduce.

**Comment by cowtowncoder** [comment]
Ok I'll see that I can reproduce this, if not will ask. :)

**Comment by cowtowncoder** [comment]
Hmmh. With simple POJO like:

```java
    static class OptionalStringBean {
        public Optional<String> value;
    }
```

and matching JSON of

```json
{"value":"xyz"}
```

I can not reproduce the problem. So I think I do need a test case.

**Comment by shanloid** [comment]
This is the code I used to produce the error pasted earlier:

https://gist.github.com/shanloid/5d28070b36ce383dc300#file-jdk8optionaltest

**Comment by cowtowncoder** [comment]
Thanks. I wonder if `@JsonCreator` matters here....

**Comment by shanloid** [comment]
Success. It works if I specify @JsonProperty on the data property in the Entity constructor. I didn't think that this would be required for a single property, especially when I've explicitly told Jackson to use the constructor, but if I add it, it works.

If this seems like a resolution, feel free to close this one.

**Comment by cowtowncoder** [comment]
I'll try to see what causes this; difficult to say if it's a simple flaw or a more fundamental problem.
Thank you for document the work-around.

**Comment by cowtowncoder** [comment]
@shanloid Ok, right; test case is incorrect here. And use of `@JsonProperty` does make sense.

With just `@JsonCreator`, what you get is that the whole JSON Object is being mapped to `Optional<String>`: this does not make sense in general, as it is not clear which properties should map where.

When adding `@JsonProperty`, you are instead mapping one specific property of incoming JSON Object into value. So in this case `@JsonProperty("data")` would extract value.

So: you found the actual solution here, and I will change the test case to reflect that as well.
