### ISSUE TITLE
With jackson it is impossible to serialize Maps that contain maps and Optional elements.

### ISSUE THREAD

**Issue by hgschmie** [FasterXML/jackson-datatype-jdk8#9]
Using the 2.4 branch (2.4.7-SNAPSHOT) with the guava and jdk8 serializer:

```java
package com.groupon.metrics.common;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.datatype.guava.GuavaModule;
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module;
import com.google.common.collect.ImmutableMap;
import org.junit.Test;

import java.util.Map;

import static org.junit.Assert.assertEquals;

public class OptionalTest
{
    public ObjectMapper getObjectMapper()
            throws Exception
    {
        ObjectMapper objectMapper = new ObjectMapper();
        objectMapper.registerModule(new GuavaModule());
        objectMapper.registerModule(new Jdk8Module());
        return objectMapper;
    }

    @Test
    public void testOptionalAbsentAlways()
            throws Exception
    {
        ObjectMapper objectMapper = getObjectMapper();
        objectMapper.setSerializationInclusion(JsonInclude.Include.ALWAYS);

        Map<String, Object> guavaMap = ImmutableMap.of(
                "key", com.google.common.base.Optional.absent(),
                "map", ImmutableMap.<String, String>of());
        Map<String, Object> jdk8Map = ImmutableMap.of(
                "key", java.util.Optional.empty(),
                "map", ImmutableMap.<String, String>of());

        String guavaResult = objectMapper.writeValueAsString(guavaMap);
        String jdk8Result = objectMapper.writeValueAsString(jdk8Map);

        assertEquals("{\"key\":null}", guavaResult);
        assertEquals(guavaResult, jdk8Result);
    }

    @Test
    public void testOptionalAbsentNonDefault()
            throws Exception
    {
        ObjectMapper objectMapper = getObjectMapper();
        objectMapper.setSerializationInclusion(JsonInclude.Include.NON_DEFAULT);

        Map<String, Object> guavaMap = ImmutableMap.of(
                "key", com.google.common.base.Optional.absent(),
                "map", ImmutableMap.<String, String>of());
        Map<String, Object> jdk8Map = ImmutableMap.of(
                "key", java.util.Optional.empty(),
                "map", ImmutableMap.<String, String>of());

        String guavaResult = objectMapper.writeValueAsString(guavaMap);
        String jdk8Result = objectMapper.writeValueAsString(jdk8Map);

        assertEquals("{\"key\":null}", guavaResult);
        assertEquals(guavaResult, jdk8Result);
    }

    @Test
    public void testOptionalAbsentNonEmpty()
            throws Exception
    {
        ObjectMapper objectMapper = getObjectMapper();
        objectMapper.setSerializationInclusion(JsonInclude.Include.NON_EMPTY);

        Map<String, Object> guavaMap = ImmutableMap.of(
                "key", com.google.common.base.Optional.absent(),
                "map", ImmutableMap.<String, String>of());
        Map<String, Object> jdk8Map = ImmutableMap.of(
                "key", java.util.Optional.empty(),
                "map", ImmutableMap.<String, String>of());

        String guavaResult = objectMapper.writeValueAsString(guavaMap);
        String jdk8Result = objectMapper.writeValueAsString(jdk8Map);

        assertEquals("{\"key\":null}", guavaResult);
        assertEquals(guavaResult, jdk8Result);
    }

    @Test
    public void testOptionalAbsentNonNull()
            throws Exception
    {
        ObjectMapper objectMapper = getObjectMapper();
        objectMapper.setSerializationInclusion(JsonInclude.Include.NON_NULL);

        Map<String, Object> guavaMap = ImmutableMap.of(
                "key", com.google.common.base.Optional.absent(),
                "map", ImmutableMap.<String, String>of());
        Map<String, Object> jdk8Map = ImmutableMap.of(
                "key", java.util.Optional.empty(),
                "map", ImmutableMap.<String, String>of());

        String guavaResult = objectMapper.writeValueAsString(guavaMap);
        String jdk8Result = objectMapper.writeValueAsString(jdk8Map);

        assertEquals("{\"key\":null}", guavaResult);
        assertEquals(guavaResult, jdk8Result);
    }
}
```

Running these tests:

```
Running com.groupon.metrics.common.OptionalTest
Tests run: 4, Failures: 4, Errors: 0, Skipped: 0, Time elapsed: 0.595 sec <<< FAILURE! - in com.groupon.metrics.common.OptionalTest
testOptionalAbsentNonEmpty(com.groupon.metrics.common.OptionalTest)  Time elapsed: 0.581 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<{"key":null[]}> but was:<{"key":null[,"map":{}]}>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.groupon.metrics.common.OptionalTest.testOptionalAbsentNonEmpty(OptionalTest.java:81)

testOptionalAbsentAlways(com.groupon.metrics.common.OptionalTest)  Time elapsed: 0.005 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<{"key":null[]}> but was:<{"key":null[,"map":{}]}>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.groupon.metrics.common.OptionalTest.testOptionalAbsentAlways(OptionalTest.java:41)

testOptionalAbsentNonDefault(com.groupon.metrics.common.OptionalTest)  Time elapsed: 0.004 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<{"key":null[]}> but was:<{"key":null[,"map":{}]}>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.groupon.metrics.common.OptionalTest.testOptionalAbsentNonDefault(OptionalTest.java:61)

testOptionalAbsentNonNull(com.groupon.metrics.common.OptionalTest)  Time elapsed: 0.005 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<{"key":null[]}> but was:<{"key":null[,"map":{}]}>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.groupon.metrics.common.OptionalTest.testOptionalAbsentNonNull(OptionalTest.java:101)
```
It is impossible to serialize a bean that contains an optional and a map the same way in jackson 2.4

With the current trunk (2.6-rc2-SNAPSHOT):

```java
package com.groupon.metrics.common;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.datatype.guava.GuavaModule;
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module;
import com.google.common.collect.ImmutableMap;
import org.junit.Test;

import java.util.Map;

import static org.junit.Assert.assertEquals;

public class OptionalTest
{
    public ObjectMapper getObjectMapper()
            throws Exception
    {
        ObjectMapper objectMapper = new ObjectMapper();
        objectMapper.registerModule(new GuavaModule());
        objectMapper.registerModule(new Jdk8Module());
        return objectMapper;
    }

    @Test
    public void testOptionalAbsentAlways()
            throws Exception
    {
        ObjectMapper objectMapper = getObjectMapper();
        objectMapper.setSerializationInclusion(JsonInclude.Include.ALWAYS);

        Map<String, Object> guavaMap = ImmutableMap.of(
                "key", com.google.common.base.Optional.absent(),
                "map", ImmutableMap.<String, String>of());
        Map<String, Object> jdk8Map = ImmutableMap.of(
                "key", java.util.Optional.empty(),
                "map", ImmutableMap.<String, String>of());

        String guavaResult = objectMapper.writeValueAsString(guavaMap);
        String jdk8Result = objectMapper.writeValueAsString(jdk8Map);

        assertEquals("{\"key\":null}", guavaResult);
        assertEquals(guavaResult, jdk8Result);
    }

    @Test
    public void testOptionalAbsentNonDefault()
            throws Exception
    {
        ObjectMapper objectMapper = getObjectMapper();
        objectMapper.setSerializationInclusion(JsonInclude.Include.NON_DEFAULT);

        Map<String, Object> guavaMap = ImmutableMap.of(
                "key", com.google.common.base.Optional.absent(),
                "map", ImmutableMap.<String, String>of());
        Map<String, Object> jdk8Map = ImmutableMap.of(
                "key", java.util.Optional.empty(),
                "map", ImmutableMap.<String, String>of());

        String guavaResult = objectMapper.writeValueAsString(guavaMap);
        String jdk8Result = objectMapper.writeValueAsString(jdk8Map);

        assertEquals("{\"key\":null}", guavaResult);
        assertEquals(guavaResult, jdk8Result);
    }

    @Test
    public void testOptionalAbsentNonEmpty()
            throws Exception
    {
        ObjectMapper objectMapper = getObjectMapper();
        objectMapper.setSerializationInclusion(JsonInclude.Include.NON_EMPTY);

        Map<String, Object> guavaMap = ImmutableMap.of(
                "key", com.google.common.base.Optional.absent(),
                "map", ImmutableMap.<String, String>of());
        Map<String, Object> jdk8Map = ImmutableMap.of(
                "key", java.util.Optional.empty(),
                "map", ImmutableMap.<String, String>of());

        String guavaResult = objectMapper.writeValueAsString(guavaMap);
        String jdk8Result = objectMapper.writeValueAsString(jdk8Map);

        assertEquals("{\"key\":null}", guavaResult);
        assertEquals(guavaResult, jdk8Result);
    }

    @Test
    public void testOptionalAbsentNonNull()
            throws Exception
    {
        ObjectMapper objectMapper = getObjectMapper();
        objectMapper.setSerializationInclusion(JsonInclude.Include.NON_NULL);

        Map<String, Object> guavaMap = ImmutableMap.of(
                "key", com.google.common.base.Optional.absent(),
                "map", ImmutableMap.<String, String>of());
        Map<String, Object> jdk8Map = ImmutableMap.of(
                "key", java.util.Optional.empty(),
                "map", ImmutableMap.<String, String>of());

        String guavaResult = objectMapper.writeValueAsString(guavaMap);
        String jdk8Result = objectMapper.writeValueAsString(jdk8Map);

        assertEquals("{\"key\":null}", guavaResult);
        assertEquals(guavaResult, jdk8Result);
    }

    @Test
    public void testOptionalAbsentNonAbsent()
            throws Exception
    {
        ObjectMapper objectMapper = getObjectMapper();
        objectMapper.setSerializationInclusion(JsonInclude.Include.NON_ABSENT);

        Map<String, Object> guavaMap = ImmutableMap.of(
                "key", com.google.common.base.Optional.absent(),
                "map", ImmutableMap.<String, String>of());
        Map<String, Object> jdk8Map = ImmutableMap.of(
                "key", java.util.Optional.empty(),
                "map", ImmutableMap.<String, String>of());

        String guavaResult = objectMapper.writeValueAsString(guavaMap);
        String jdk8Result = objectMapper.writeValueAsString(jdk8Map);

        assertEquals("{\"key\":null}", guavaResult);
        assertEquals(guavaResult, jdk8Result);
    }
}
```

Running the same test with all five settings:

```
Running com.groupon.metrics.common.OptionalTest
Tests run: 5, Failures: 5, Errors: 0, Skipped: 0, Time elapsed: 0.528 sec <<< FAILURE! - in com.groupon.metrics.common.OptionalTest
testOptionalAbsentNonAbsent(com.groupon.metrics.common.OptionalTest)  Time elapsed: 0.508 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<{"key":null[]}> but was:<{"key":null[,"map":{}]}>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.groupon.metrics.common.OptionalTest.testOptionalAbsentNonAbsent(OptionalTest.java:126)

testOptionalAbsentNonEmpty(com.groupon.metrics.common.OptionalTest)  Time elapsed: 0.003 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<{"key":null[]}> but was:<{"key":null[,"map":{}]}>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.groupon.metrics.common.OptionalTest.testOptionalAbsentNonEmpty(OptionalTest.java:84)

testOptionalAbsentAlways(com.groupon.metrics.common.OptionalTest)  Time elapsed: 0.004 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<{"key":null[]}> but was:<{"key":null[,"map":{}]}>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.groupon.metrics.common.OptionalTest.testOptionalAbsentAlways(OptionalTest.java:42)

testOptionalAbsentNonDefault(com.groupon.metrics.common.OptionalTest)  Time elapsed: 0.004 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<{"key":null[]}> but was:<{"key":null[,"map":{}]}>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.groupon.metrics.common.OptionalTest.testOptionalAbsentNonDefault(OptionalTest.java:63)

testOptionalAbsentNonNull(com.groupon.metrics.common.OptionalTest)  Time elapsed: 0.003 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<{"key":null[]}> but was:<{"key":null[,"map":{}]}>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.groupon.metrics.common.OptionalTest.testOptionalAbsentNonNull(OptionalTest.java:105)

Running com.groupon.metrics.common.MetricsPayloadTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.152 sec - in com.groupon.metrics.common.MetricsPayloadTest
Running com.groupon.metrics.common.StenoEnvelopeTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.015 sec - in com.groupon.metrics.common.StenoEnvelopeTest
```
Results :

Failed tests: 
  OptionalTest.testOptionalAbsentAlways:42 expected:<{"key":null[]}> but was:<{"key":null[,"map":{}]}>
  OptionalTest.testOptionalAbsentNonAbsent:126 expected:<{"key":null[]}> but was:<{"key":null[,"map":{}]}>
  OptionalTest.testOptionalAbsentNonDefault:63 expected:<{"key":null[]}> but was:<{"key":null[,"map":{}]}>
  OptionalTest.testOptionalAbsentNonEmpty:84 expected:<{"key":null[]}> but was:<{"key":null[,"map":{}]}>
  OptionalTest.testOptionalAbsentNonNull:105 expected:<{"key":null[]}> but was:<{"key":null[,"map":{}]}>

It is also impossible with Jackson 2.6 to serialize a map containing an Optional and an empty map the same way for JDK8 and Guava optionals.

These behaviors should be identical.

**Comment by hgschmie** [comment]
let's redo that...

**Comment by cowtowncoder** [comment]
Not sure if it could help, but 2.6 Guava module has one more configurable setting, via `configureAbsentsAsNulls()`. Default value is `true`, which is supposed to keep the old handling of `Optional.absent()` as `null` equivalent. `false` would make Guava follow same rules as JDK8 optional and other referential types, which is defined as the standard way going forward.
